version: '3'
services:
    pro-epargne-admin-ui:
        image: mchekini/pro-epargne-admin-ui:1.0
        container_name: pro-epargne-admin-ui
        ports:
            - "80:80"


networks:
    default:
        external:
            name: pro-epargne
